#!/usr/bin/env bash
set -euo pipefail

# JCut cleanup helper
# Default behavior is conservative: remove debug artifacts and backup files.
# Optional flags can reset history/state JSON safely.

PROJECT_DIR_DEFAULT="/mnt/Cancer/PanelVid2TikTok/Politics/projects/default"
REPO_ROOT_DEFAULT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PROJECT_DIR="$PROJECT_DIR_DEFAULT"
REPO_ROOT="$REPO_ROOT_DEFAULT"
RESET_HISTORY=0
RESET_STATE=0

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --project-dir PATH    Project directory containing state.json/history.json
                        (default: $PROJECT_DIR_DEFAULT)
  --repo-root PATH      JCut repo root (for debug/ cleanup)
                        (default: script directory)
  --reset-history       Replace history.json with empty valid history object
  --reset-state         Replace state.json with empty JSON object {}
  --help                Show this help

Examples:
  $0
  $0 --reset-history
  $0 --project-dir /path/to/projects/default --reset-history --reset-state
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-dir)
      PROJECT_DIR="${2:-}"
      shift 2
      ;;
    --repo-root)
      REPO_ROOT="${2:-}"
      shift 2
      ;;
    --reset-history)
      RESET_HISTORY=1
      shift
      ;;
    --reset-state)
      RESET_STATE=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ! -d "$PROJECT_DIR" ]]; then
  echo "Project dir not found: $PROJECT_DIR" >&2
  exit 1
fi

mkdir -p "$PROJECT_DIR"

# Remove large debug artifacts produced by speaker flow runs.
if [[ -d "$REPO_ROOT/debug/speaker_flow" ]]; then
  rm -rf "$REPO_ROOT/debug/speaker_flow"
fi

# Remove transient Python bytecode cache generated by scripts.
if [[ -d "$REPO_ROOT/__pycache__" ]]; then
  rm -rf "$REPO_ROOT/__pycache__"
fi

# Remove autosave and pre-restore backup files in the active project.
find "$PROJECT_DIR" -maxdepth 1 -type f -name 'state_backup_*.json' -delete
find "$PROJECT_DIR" -maxdepth 1 -type f -name '*.pre_restore_*' -delete

# Optionally reset history/state while preserving valid JSON structures expected by app.
if [[ "$RESET_HISTORY" -eq 1 ]]; then
  cat > "$PROJECT_DIR/history.json" <<'EOF'
{
  "entries": [],
  "index": -1
}
EOF
fi

if [[ "$RESET_STATE" -eq 1 ]]; then
  cat > "$PROJECT_DIR/state.json" <<'EOF'
{}
EOF
fi

# Print compact summary.
if command -v du >/dev/null 2>&1; then
  echo "Cleanup complete."
  du -sh "$PROJECT_DIR" 2>/dev/null || true
  if [[ -d "$REPO_ROOT/debug" ]]; then
    du -sh "$REPO_ROOT/debug" 2>/dev/null || true
  fi
fi
