#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba8) uniform image2D destinationImage;
layout(binding = 1, rgba8) readonly uniform image2D sourceImage;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(destinationImage);
    if (pixel.x >= size.x || pixel.y >= size.y) {
        return;
    }
    vec4 source = imageLoad(sourceImage, pixel);
    vec4 destination = imageLoad(destinationImage, pixel);
    float inverseAlpha = 1.0 - source.a;
    imageStore(
        destinationImage,
        pixel,
        vec4(
            source.rgb * source.a +
                destination.rgb * inverseAlpha,
            source.a + destination.a * inverseAlpha));
}
